# 
# Synthesis run script generated by Vivado
# 

set_param simulator.questaInstallPath /opt/applics/questasim-10.5c_4/questasim
set_param simulator.modelsimInstallPath /opt/applics/questasim-10.5c_4/questasim
create_project -in_memory -part xc7vx690tffg1761-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/hdk3.cache/wt [current_project]
set_property parent.project_path /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/hdk3.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/hdk3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/mm/CSA_carry.v
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/mm/RAM_control.v
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/mm/circular_buffer1.v
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/mm/circular_buffer2.v
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/mm/matix_mul.v
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/mm/multiply_accumulator.v
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/mm/normalization.v
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/mm/output_buffer.v
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/mm/unum_CSA.v
}
read_vhdl -library xil_defaultlib {
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/vivado_ipsyn/blk_mem_gen_v8_3.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/vivado_ipsyn/blk_mem_gen_v8_3_vhsyn_rfs.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/vivado_ipsyn/ma_ram.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/top/psl_accel.vhdl
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/vivado_ipsyn/ram_input1.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/vivado_ipsyn/ram_input2.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/vivado_ipsyn/ram_output.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/top/psl_fpga.vhdl
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/lib/functions.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/lib/psl.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/pkg/frame_package.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/pkg/dma_package.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/lib/wed.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/pkg/cu_package.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/pkg/control_package.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/pkg/mmio_package.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/rtl/cu.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/rtl/control.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/rtl/mmio.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/rtl/ram.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/rtl/fifo.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/rtl/dma.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/rtl/frame.vhd
  /shares/bulk/jianyuchen/capi_development_kit3/alphadata/adv7_capi_1_1_release/Sources/afu/rtl/afu.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top psl_fpga -part xc7vx690tffg1761-2L


write_checkpoint -force -noxdef psl_fpga.dcp

catch { report_utilization -file psl_fpga_utilization_synth.rpt -pb psl_fpga_utilization_synth.pb }
